sculpin_content_types:
  posts:
    singular_name: post
    type: path
    path: _posts
    permalink: blog/:year/:month/:slug_title
    taxonomies:
      - tags
      - categories
  pages:
    singular_name: page
    permalink: :basename
    type: path
    path: _pages
  authors:
    singular_name: author
    permalink: authors/:basename
    type: path
    path: _authors
  psr:
    permalink: psr/:basename
    type: path
    path: _psr
  bylaws:
    singular_name: bylaw
    permalink: bylaws/:slug_title
    type: path
    path: _bylaws

sculpin:
  ignore: ["**/*.scss"]

services:
  fig.website.external_process_markdown_engine:
    class: Fig\Website\ExternalProcessMarkdownEngine
    arguments:
      $command: "bundle exec kramdown -i GFM --syntax-highlighter rouge --no-hard-wrap"
  fig.website.link_processor_extension:
    class: Fig\Website\TwigLinkProcessor
    tags:
      - { name: twig.extension }
  aptoma.twig.markdown_extension:
    class: Aptoma\Twig\Extension\MarkdownExtension
    arguments:
      $markdownEngine: '@fig.website.external_process_markdown_engine'
    tags:
      - { name: twig.extension }
