sculpin_content_types:
  posts:
    enabled: false
  psrs:
    singular_name: psr
    permalink: psr/:slug_title
    type: path
    path: psr
  bylaws:
    singular_name: bylaw
    permalink: bylaws/:slug_title
    type: path
    path: bylaws

sculpin:
  ignore: ["**/*.scss"]

services:
  aptoma.twig.markdown_engine:
    class: Aptoma\Twig\Extension\MarkdownEngine\MichelfMarkdownEngine
  aptoma.twig.markdown_extension:
    class: Aptoma\Twig\Extension\MarkdownExtension
    arguments:
      $markdownEngine: '@aptoma.twig.markdown_engine'
    tags:
      - { name: twig.extension }
  ramsey.twig.codeblock_extension:
    class: Ramsey\Twig\CodeBlock\CodeBlockExtension
    tags:
      - { name: twig.extension }
