https://www.{default}/:
  type: upstream
  upstream: php-fig-website:http
  cache:
    enabled: true

https://{default}/:
  type: redirect
  to: https://www.{default}/

# todo: remove as soon as DNS propagates and LetsEncrypt can verify the domain
http://www.{default}/:
  type: upstream
  upstream: php-fig-website:http
  cache:
    enabled: true
# /todo

# todo: uncomment as soon as DNS propagates and LetsEncrypt can verify the domain
#http://{default}/:
#  type: redirect
#  to: https://www.{default}/
# /todo
